### ISSUE TITLE
Cannot add a configuration with name 'testCompile' as a configuration with that name already exists

### ISSUE THREAD

**Issue by rallat** [JCAndKSolutions/android-unit-test#42]
I am getting this error when I add this line to my build.gradle after android {} block

```
apply plugin: 'android-unit-test'
```

This is the debug error:

```
19:40:40.016 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.InvalidUserDataException: Cannot add a configuration with name 'testCompile' as a configuration with that name already exists.
19:40:40.016 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.DefaultNamedDomainObjectCollection.assertCanAdd(DefaultNamedDomainObjectCollection.java:95)
19:40:40.016 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:56)
19:40:40.017 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:40)
19:40:40.017 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.NamedDomainObjectContainer$create.call(Unknown Source)
19:40:40.017 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.ConfigurationManager.createTestCompileTaskConfiguration(ConfigurationManager.groovy:36)
19:40:40.018 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.ConfigurationManager.createNewConfigurations(ConfigurationManager.groovy:32)
19:40:40.018 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.ConfigurationManager$createNewConfigurations.call(Unknown Source)
19:40:40.018 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.MainHandler.run(MainHandler.groovy:24)
19:40:40.019 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.MainHandler$run.call(Unknown Source)
19:40:40.019 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.AndroidUnitTestPlugin.apply(AndroidUnitTestPlugin.groovy:23)
19:40:40.019 [ERROR] [org.gradle.BuildExceptionReporter]    at com.jcandksolutions.gradle.androidunittest.AndroidUnitTestPlugin.apply(AndroidUnitTestPlugin.groovy)
19:40:40.020 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:104)
19:40:40.020 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:68)
19:40:40.020 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:34)
19:40:40.020 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:116)
19:40:40.021 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
19:40:40.021 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:85)
19:40:40.021 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:129)
19:40:40.021 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:41)
19:40:40.022 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.Project$apply.call(Unknown Source)
19:40:40.022 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
19:40:40.022 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.Script$apply.callCurrent(Unknown Source)
19:40:40.023 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
19:40:40.023 [ERROR] [org.gradle.BuildExceptionReporter]    ... 56 more
```

Any idea how can I fix this?
Thanks

**Comment by aarushi24** [comment]
I'm getting the same problem. How do I find this plugin?

**Comment by JurgenCruz** [comment]
If you mean, how do you find the duplicate plug in, thne just remove one plugin at a time and see what happens. But in any case, this plugin is deprecated and should not be used with the latest android plugin.
