### ISSUE TITLE
Application is instantiated twice or more

### ISSUE THREAD

**Issue by lapastillaroja** [JCAndKSolutions/android-unit-test#98]
I'm trying to execute 2 unit tests but they always fail in the initalization/destruction of the
application class. 

```java
public class MyApplication extends com.activeandroid.app.Application {
    @Override
    public void onCreate() {
        super.onCreate();

        ActiveAndroid.initialize(this);

        // Glide
        Glide.setup(new GlideBuilder(this).setDiskCache(
                DiskLruCacheWrapper.get(Glide.getPhotoCacheDir(this), 50 * 1024 * 1024)));
        Glide.get(this).register(GlideUrl.class, InputStream.class,
                new OkHttpUrlLoader.Factory(new OkHttpClient()));
    }

    @Override
    public void onTerminate() {
        ActiveAndroid.dispose();
        super.onTerminate();
    }
```
Error 1
```
java.lang.NullPointerException
    at com.activeandroid.Cache.closeDatabase(Cache.java:110)
    at com.activeandroid.Cache.dispose(Cache.java:88)
    at com.activeandroid.ActiveAndroid.dispose(ActiveAndroid.java:52)
    at com.activeandroid.app.Application.onTerminate(Application.java:31)
    at com.example.MyApplication.onTerminate(MyApplication.java:88)
    at org.robolectric.internal.ParallelUniverse.tearDownApplication(ParallelUniverse.java:133)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:242)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:172)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Error 2
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Glide is already setup, check with isSetup() first
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:232)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:172)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Glide is already setup, check with isSetup() first
    at com.bumptech.glide.Glide.setup(Glide.java:176)
    at com.example.MyApplication.onCreate(MyApplication.java:64)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:126)
    at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:431)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:228)
    ... 35 more
```
It seems that Glide and ActiveAndroid fail because they are called twice. I thought maybe tests are executed in parallel or in the same JVM so I tried changing  the `maxParallelForks` and `forkEvery` config options but nothing changed.   
Same problem occurs with Robolectric 2.4 and 3-SNAPSHOT.

Any idea of why is this happening?

I'm using android-test-unit's version 2.1.1

Simplified build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'retrolambda'

// Testing
apply plugin: 'android-unit-test'

androidUnitTest {
    testTasks {
        all {
            systemProperty 'android.assets', './src/test/assets'
        }
    }
}

repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile 'com.android.support:support-v4:21.+'
    compile 'com.android.support:support-v13:21.+'

    // ImageLoader
    compile 'com.github.bumptech.glide:glide:3.4.+'
    compile 'com.github.bumptech.glide:okhttp-integration:1.1.+'
    // ORM
    compile 'com.michaelpardo:activeandroid:3.1.+'

    // Test libraries
    testCompile 'junit:junit:4.+'
    testCompile 'org.robolectric:robolectric:3.+'
    testCompile 'org.assertj:assertj-core:1.7.+'
}
```

Maybe related robolectric issue
https://github.com/robolectric/robolectric/issues/595

**Comment by SuperJugy** [comment]
Since I don't see your tests, I can't know if there is something wrong with them. All I can see from your stacktrace is that there is a NullPointerException in a third party library and an IlegalArgumentException also in a third party library. I see you are using the Robolectric runner and the tests are running so the plug in is working. My advise would be to either show your tests or take it to robolectric since I don't see anything related to this plugin.

**Comment by lapastillaroja** [comment]
These are my test as they are.
I'm using Dagger too and a local json client to read json files from the assets directory.
```java

@RunWith(RobolectricTestRunner.class)
@Config(emulateSdk = 18)
public class SiteDaoTest {

    @Inject
    RestAdapter mRestAdapter;
    @Inject
    Client client;

    @Module(
            includes = ApiModule.class,
            injects = {SiteDaoTest.class},
            overrides = true,
            complete = false
    )
    class TestApiModule {

        @Provides
        @Singleton
        public RestAdapter provideRestAdapter(Client client, Converter converter) {
            return new RestAdapter.Builder()
                    .setEndpoint(Endpoint.getApi())
                    .setClient(client)
                    .setConverter(converter)
                    .setRequestInterceptor(new RequestInterceptor())
                    .setExecutors(AsyncTask.THREAD_POOL_EXECUTOR,
                            new MainThreadExecutor())
                    .build();
        }

        @Provides
        @Singleton
        public Client provideHttpClient() {
            return new LocalJsonClient(ShadowApplication.getInstance().getApplicationContext());
        }
    }

    @Before
    public void setUp() {
        ObjectGraph.create(
                new TestApiModule(),
                new ApiModule()).inject(this);
    }

    @Test
    public void testAsertTrue() throws Exception {
        assertThat(true).isTrue();
    }

    @Test
    public void testPost_failApiPostSite() throws Exception {

        // fail call
        ((LocalJsonClient) client).setScenario("fail");

        BlogPost blogPost = mRestAdapter.create(BlogPost.class);

        BlogPostDto blogData = new BlogPostDto();
        blogData.blogId = "1";

        blogPost.post(blogData).subscribe(
                baseDto -> Assert.assertThat(baseDto.meta.code, is(not(200))),
                throwable -> Assert.fail());
    }
}
```

**Comment by SuperJugy** [comment]
Well, you are marking the method `provideHttpClient()` with `@Singleton`. it will make that static state. don't make it a singleton. and about the nullpointer exception I do not know what is happening, try debugging.
